// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8pD_UU6ky0RyDsoQffMOTnLoANOd4bSA',
    appId: '1:607005935891:web:b8702b86822c3012f632e6',
    messagingSenderId: '607005935891',
    projectId: 'delivery-app-1fbbe',
    authDomain: 'delivery-app-1fbbe.firebaseapp.com',
    storageBucket: 'delivery-app-1fbbe.appspot.com',
    measurementId: 'G-PCM199XN2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHvhQnzLUKvahQOcAZF90GX_pGfBhPeMs',
    appId: '1:607005935891:android:e1cd7b6401c17718f632e6',
    messagingSenderId: '607005935891',
    projectId: 'delivery-app-1fbbe',
    storageBucket: 'delivery-app-1fbbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD28reTBbt3kpUN4mlgIFSnSF6Ilv5hLaU',
    appId: '1:607005935891:ios:f511eabbf3c57f9af632e6',
    messagingSenderId: '607005935891',
    projectId: 'delivery-app-1fbbe',
    storageBucket: 'delivery-app-1fbbe.appspot.com',
    iosClientId: '607005935891-3tid2bkdod2m4k9ias486g8pu2eha73i.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD28reTBbt3kpUN4mlgIFSnSF6Ilv5hLaU',
    appId: '1:607005935891:ios:f511eabbf3c57f9af632e6',
    messagingSenderId: '607005935891',
    projectId: 'delivery-app-1fbbe',
    storageBucket: 'delivery-app-1fbbe.appspot.com',
    iosClientId: '607005935891-3tid2bkdod2m4k9ias486g8pu2eha73i.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
